import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

import ConfigureAmplifyClientSide from "./components/ConfigureAmplifyClientSide";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ConfigureAmplifyClientSide />
      <body className={inter.className}>{children}</body>
    </html>
  );
}

