// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const config = {
  API: {
    GraphQL: {
      endpoint: "http://localhost:4001/graphql",
      region: "ap-northeast-1",
      defaultAuthMode: "apiKey",
      apiKey: "da2-fakeApiId123456",
    },
  },
};

export default config;
