// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const config =  {
    API: {
      GraphQL: {
        endpoint: 'https://kxzzlcwruberfmxxx2iub67t6i.appsync-api.ap-northeast-1.amazonaws.com/graphql',
        region: 'ap-northeast-1',
        defaultAuthMode: 'apiKey',
        apiKey: 'da2-2jrglsj55fbxdf7fvpzse5d2k4'
      }
    }
};

export default config;

